# Generated by Django 4.2.5 on 2024-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.TextField(
                blank=True,
                choices=[
                    ("actor", "Actor"),
                    ("writer", "Writer"),
                    ("director", "Director"),
                ],
                max_length=50,
                verbose_name="Role",
            ),
        ),
    ]
